# Generated by Django 4.2.7 on 2026-02-16 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classifier', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classification',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Classifications'},
        ),
        migrations.AddField(
            model_name='classification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classification',
            name='image',
            field=models.ImageField(upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('two_fa_enabled', models.BooleanField(default=True)),
                ('two_fa_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TwoFactorToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=6, unique=True)),
                ('purpose', models.CharField(choices=[('signup', 'Account Creation'), ('login', 'Login Verification'), ('update_email', 'Email Update')], default='login', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two_fa_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
